# Generated by Django 3.2 on 2022-03-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Neutral')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
